Repository laminas/laminas-cache-storage-adapter-filesystem, pull requests merged in 2024-07, with the labels that each got.

#90 Add support `laminas-cache` v4
  .laminas-ci.json
  benchmark/FilesystemStorageAdapterBench.php
  composer.json
  composer.lock
  phpbench.json
  phpunit.xml.dist
  psalm-baseline.xml
  psalm.xml.dist
  src/Filesystem.php
  src/Filesystem/AdapterPluginManagerDelegatorFactory.php
  src/Filesystem/Exception/MetadataException.php
  src/Filesystem/LocalFilesystemInteraction.php
  src/Filesystem/Metadata.php
  src/FilesystemIterator.php
  src/FilesystemOptions.php
  test/integration/Psr/CacheItemPool/FilesystemIntegrationTest.php
  test/integration/Psr/SimpleCache/FilesystemIntegrationTest.php
  test/unit/Filesystem/AdapterPluginManagerDelegatorFactoryTest.php
  test/unit/FilesystemOptionsTest.php
  test/unit/FilesystemTest.php
Labels: BC Break, Enhancement

#91 Introduce TTL per item along with value serialization
  composer.json
  composer.lock
  psalm-baseline.xml
  src/Filesystem.php
  src/Filesystem/Clock.php
  src/Filesystem/FilesystemInteractionInterface.php
  src/Filesystem/LocalFilesystemInteraction.php
  src/FilesystemOptions.php
  test/integration/Psr/CacheItemPool/FilesystemIntegrationTest.php
  test/integration/Psr/SimpleCache/FilesystemIntegrationTest.php
  test/unit/Filesystem/TestAsset/DelayedFilesystemInteraction.php
  test/unit/Filesystem/TestAsset/ModifiableClock.php
  test/unit/Filesystem/TestAsset/SerializableObject.php
  test/unit/FilesystemOptionsTest.php
  test/unit/FilesystemTest.php
Labels: BC Break, Enhancement

#88 Corrected link to documentation
  README.md
Labels: Documentation

#84 Ignore nonexistent system temporary directory when a valid cache directory is provided via options
  src/FilesystemOptions.php
  test/unit/Filesystem/TestAsset/instantiate_filesystem_options_with_cache_dir.php
  test/unit/FilesystemOptionsTest.php
Labels: Bug

#97 Introduce modifiable clock from `laminas-cache-storage-adapter-test` v4.1
  composer.json
  composer.lock
  test/integration/Psr/CacheItemPool/FilesystemIntegrationTest.php
  test/integration/Psr/SimpleCache/FilesystemIntegrationTest.php
  test/unit/Filesystem/TestAsset/ModifiableClock.php
  test/unit/FilesystemTest.php
Labels: Enhancement

#96 Prevent double serialization when `Serializer` plugin is used
  src/Filesystem.php
Labels: Enhancement
